// Recorded from the article scene headlessly (bun-webgpu, pinned Shallot): 280 px square canvas,
// 9 px cells, camera distance 1.95, pitch 0.55, phase 0.1, white albedo. The no-WebGPU rest frame.
export const cubeFrame = [
  "                               ",
  "                               ",
  "                               ",
  "                               ",
  "             ---               ",
  "          -----------          ",
  "       -----/jjj\\--------\\\\    ",
  "   //---//jjjjjjjjjjjj\\\\\\|     ",
  "   |||\\--\\jjjjjjjjjjjj///|     ",
  "    |\\------\\jjjjjjj////||     ",
  "    |\\i\\-------\\jjj////u||     ",
  "    ||iiii\\-------////uu||     ",
  "    ||iiiiiii\\----///uu/|      ",
  "     |iiiiiiiiii\\-/uuuu||      ",
  "     |\\iiiiiiiiii||uuuu||      ",
  "     ||iiiiiiiiii||uuuu||      ",
  "     ||iiiiiiiiii||uuuu|       ",
  "      |\\iiiiiiiii||uuu/|       ",
  "      |\\iiiiiiiii||uuu//       ",
  "      |\\iiiiiiiii||uu//        ",
  "      \\\\\\\\iiiiiii||u///        ",
  "        \\\\\\iiiiii||u//         ",
  "         \\\\\\\\iii||///          ",
  "           \\\\\\ii||//           ",
  "             \\\\\\-///           ",
  "              \\\\-//            ",
  "                -/             ",
  "                               ",
  "                               ",
  "                               ",
  "                               ",
];
